#pragma config(Sensor, in1,    left_lf,        sensorLineFollower)
#pragma config(Sensor, in2,    mid_lf,         sensorLineFollower)
#pragma config(Sensor, in3,    right_lf,       sensorLineFollower)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// I know it is silly, but it seem that the compiler of ROBOTC does not know how to compile from multiple files.

#include "motor.c"

task main()
{
	int lowIR = 1000; //Arbitrary high number so the calibration will work
  int highIR = 0;

  //Auto-calibration ended by button press. The button will begin the line following.
  //During this time, the robot should be moved so that it sees both black and white -
  //you could 'scan' it across the line.
  for(int i=0;i<100;i++){
  	writeDebugStreamLine("left %ld mid %ld right %ld; low %ld high %ld",
			SensorValue[left_lf],
			SensorValue[mid_lf],
			SensorValue[right_lf],
			lowIR,
			highIR
		);
    if(SensorValue[mid_lf] > highIR) {
      highIR = SensorValue[mid_lf];
      } else if(SensorValue[mid_lf] < lowIR) {
      lowIR = SensorValue[mid_lf];
    }
    delay(200);
  }

  int threshold = (lowIR+highIR)>>1;

	while(true) {
		writeDebugStreamLine("left %s mid %s right %s",
			SensorValue[left_lf]>threshold?"White":"Black",
			SensorValue[mid_lf]>threshold?"White":"Black",
			SensorValue[right_lf]>threshold?"White":"Black"
		);
		delay(200);
	}
}
