#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int left_speed = 0;
int right_speed = 0;

task run_motor();
task _test_motor();

/*
void _pwm_single(int port, int hghtime, int tottime) {
	if (hghtime > 0) {
		motor[port] = 127;
	}
	else {
		motor[port] = -127;
		hghtime *= -1;
	}
	delay(hghtime);
	motor[port] = 0;
	delay(tottime-hghtime);
}
*/


task run_motor() {
	while (true) {
		motor[port1] = left_speed;
		motor[port10] = right_speed;
		writeDebugStreamLine("left %d right %d", left_speed, right_speed);
		wait1Msec(1);
	}
}

task _test_motor () {
	while (true) {
		left_speed = -80;
		right_speed = 80;
		wait1Msec(1000);
		left_speed = 80;
		right_speed = -80;
		wait1Msec(1000);
	}
}
